version: '3'

services:

  node:
    build: 
      context: ./node
    image: gabrielsantos/node
    container_name: node-challenger
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    volumes: 
      - ./node:/usr/src/app
    networks:
      - challenger-network
    depends_on:
      - database

  nginx:
    build: 
      context: ./nginx
    image: gabrielsantos/nginx
    container_name: nginx-challenger
    networks:
      - challenger-network
    ports: 
      - "8080:80"

  database:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "nodedb"
    ports:
      - "3306:3306"
    volumes:
      - /mysql/db:/docker-entrypoint-initdb.d
      - /mysql/database:/var/lib/mysql
    networks:
      - challenger-network
  
networks:
  challenger-network:
    driver: bridge